name: Test

on:
  workflow_dispatch:
  pull_request:

jobs:
  Test:
    name: Unit tests pass
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - id: cache
        uses: actions/cache@v4
        with:
          path: |
            .build
            .swiftpm
          key: ${{ runner.os }}-cache
      - run: swift test
